### ISSUE TITLE
FATAL EXCEPTION: GLThread 4718

### ISSUE THREAD

**Issue by Dn-a** [khalithartmann/flutter_arcore_plugin#15]
hi, when I try to run the app in debug mode, I get this error

```
Launching lib\main.dart on LG H870 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Waiting for LG H870 to report its views...
Debug service listening on ws://127.0.0.1:56101/Z8fh7JN4v7k=/ws
Syncing files to device LG H870...
D/PhoneWindow( 7394): windowLightStatusBar : false, disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
I/TouchFilterInputStageHelper( 7394): [needTouchEventFilter] Displayid : 66
E/AndroidRuntime( 7394): FATAL EXCEPTION: GLThread 4718
E/AndroidRuntime( 7394): Process: com.dna.augment_2, PID: 7394
E/AndroidRuntime( 7394): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.Context.getAssets()' on a null object reference
E/AndroidRuntime( 7394): 	at common.rendering.ShaderUtil.readRawTextFileFromAssets(ShaderUtil.java:86)
E/AndroidRuntime( 7394): 	at common.rendering.ShaderUtil.loadGLShader(ShaderUtil.java:36)
E/AndroidRuntime( 7394): 	at common.rendering.BackgroundRenderer.createOnGlThread(BackgroundRenderer.java:102)
E/AndroidRuntime( 7394): 	at com.peqas.arcoreplugin.FlutterArcoreView.onSurfaceCreated(FlutterArcoreView.java:258)
E/AndroidRuntime( 7394): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1539)
E/AndroidRuntime( 7394): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
W/libEGL  ( 7394): EGLNativeWindowType 0x7b25f44010 disconnect failed
W/System  ( 7394): A resource failed to call release. 
```

**Comment by ketulrastogi** [comment]
**The same error occurred while debugging my app. Here are the error details.**


E/AndroidRuntime( 6386): FATAL EXCEPTION: GLThread 21344
E/AndroidRuntime( 6386): Process: in.bugle.deshgujarat, PID: 6386
E/AndroidRuntime( 6386): **java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.AssetManager android.content.Context.getAssets()' on a null object reference**
E/AndroidRuntime( 6386):        at common.rendering.ShaderUtil.readRawTextFileFromAssets(ShaderUtil.java:86)
E/AndroidRuntime( 6386):        at common.rendering.ShaderUtil.loadGLShader(ShaderUtil.java:36)
E/AndroidRuntime( 6386):        at common.rendering.BackgroundRenderer.createOnGlThread(BackgroundRenderer.java:102)
E/AndroidRuntime( 6386):        at com.peqas.arcoreplugin.FlutterArcoreView.onSurfaceCreated(FlutterArcoreView.java:258)
E/AndroidRuntime( 6386):        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1539)
E/AndroidRuntime( 6386):        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
V/FA      ( 6386): Recording user engagement, ms: 201519
V/FA      ( 6386): Connecting to remote service
V/FA      ( 6386): Activity paused, time: 186106866
D/FA      ( 6386): Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=201519, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-5594139744625415345}]
V/FA      ( 6386): Connection attempt already in progress
D/FA      ( 6386): Connected to remote service
V/FA      ( 6386): Processing queued up service tasks: 2
I/flutter ( 6386): TempPath: /data/user/0/in.bugle.deshgujarat/cache
V/FA      ( 6386): Inactivity, disconnecting from the service
Lost connection to device.

**Comment by SamuelIGT** [comment]
I'm getting the same error.
Did anyone find a solution for this?
